"""Text hygiene: no mojibake anywhere, no missing Spanish accents in visible text.

Why this exists
---------------
Until 2026-09-25 the visible Spanish of the site was written without accents
("Analisis", "senal", "Como se usa"). It was an accident, not a policy: the
toolchain is UTF-8 end to end, but PowerShell 5.1 (Get-Content/Set-Content)
and the cp1252 Python console are not, and ASCII was the path of least
resistance. Two guards close it:

1. Mojibake markers (UTF-8 read as cp1252 and written back) must not appear in
   any tracked text file. Those sequences are never legitimate here.
2. A missing-accent guard over the Spanish text that reaches the visitor. It
   only knows UNAMBIGUOUS patterns: words that are always accented in Spanish
   ("analisis", "-cion"). Ambiguous pairs (que/qué, como/cómo, esta/está,
   mas/más) are deliberately left out: a guard that cries wolf gets disabled.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]

# UTF-8 bytes decoded as cp1252: A-tilde + a continuation byte (what an accented
# vowel or n-tilde becomes), a-circumflex + euro sign (smart quotes, dashes),
# A-circumflex before a Latin-1 symbol; the replacement char and a stray BOM.
# Written as escapes so this file does not trip its own test.
MOJIBAKE = re.compile(
    "\u00c3[\u0080-\u00bf]|\u00e2\u20ac|\u00c2[\u00a0-\u00bf]|\ufffd|\ufeff"
)

TEXT_SUFFIXES = {
    ".md", ".py", ".ts", ".mjs", ".js", ".json", ".css", ".html", ".txt",
    ".toml", ".yml", ".yaml", ".svg", ".xml",
}
SKIP_DIRS = {"node_modules", "dist", ".git", "__pycache__", "public", "shots", ".venv"}


def _text_files():
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(ROOT).parts):
            continue
        # data/dist is generated by the pipeline and checked by its own tests.
        if path.relative_to(ROOT).parts[:2] == ("data", "dist"):
            continue
        yield path


def test_no_mojibake_in_tracked_text():
    bad = []
    for path in _text_files():
        text = path.read_text(encoding="utf-8")
        for m in MOJIBAKE.finditer(text):
            line = text.count("\n", 0, m.start()) + 1
            bad.append(f"{path.relative_to(ROOT)}:{line}: {m.group(0)!r}")
    assert not bad, "mojibake:\n" + "\n".join(bad[:30])


# Words that are ALWAYS written with an accent (or ñ) in Spanish. Whole words,
# case-insensitive. Suffix rules cover the productive families.
ALWAYS_ACCENTED = [
    r"\w+cion", r"\w+sion",  # -ción/-sión singular; the plural has no accent
    r"analisis", r"sintetic\w*", r"senal(es)?", r"biologi\w*",
    r"numeros?", r"paginas?", r"tambien", r"despues", r"segun", r"ademas",
    r"geneticos?", r"geneticas?", r"genomicos?", r"genomicas?", r"codigos?",
    r"metodos?", r"estadistic\w*", r"regions?", r"unicos?", r"unicas?",
    r"tecnic\w*", r"especific\w*", r"cientific\w*", r"ultim[oa]s?", r"minim[oa]s?",
    r"maxim[oa]s?", r"lineas?", r"indigenas?", r"amerindigenas?", r"hipotesis",
    r"categorias?", r"ontologias?", r"metricas?", r"graficos?", r"basic[oa]s?",
    r"clinic[oa]s?", r"debil", r"facil", r"dificil", r"movil", r"caracter",
    r"razon", r"pestanas?", r"union", r"exon", r"intron", r"tamanos?",
    r"disenos?", r"espanol", r"automatic\w*", r"dinamic\w*", r"practic[oa]s?",
    r"calibracion", r"vias?", r"dias?", r"anos?",
    r"interaccion", r"rapid[oa]s?", r"electronic\w*", r"tipic[oa]s?",
    r"quimic\w*", r"fisic\w*", r"historic\w*", r"periodos?", r"heroe",
    r"guia", r"indices?", r"catalogos?", r"variacion", r"mutacion",
    r"poblacion", r"prediccion",
]
ACCENT_RE = re.compile(r"\b(" + "|".join(ALWAYS_ACCENTED) + r")\b", re.IGNORECASE)

# Loanwords and identifiers that match a pattern but are correct as written.
ALLOWED: set[str] = set()


def _visible_html(text: str) -> str:
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.S)
    text = re.sub(r"<(script|style)\b.*?</\1>", " ", text, flags=re.S | re.I)
    return re.sub(r"<[^>]+>", " ", text)


def _json_strings(obj):
    if isinstance(obj, dict):
        for v in obj.values():
            yield from _json_strings(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _json_strings(v)
    elif isinstance(obj, str):
        yield obj


def spanish_visible_sources():
    """(label, text) for every piece of Spanish text that reaches a visitor."""
    html = ROOT / "web" / "index.html"
    yield "web/index.html", _visible_html(html.read_text(encoding="utf-8"))
    for path in sorted((ROOT / "web" / "src" / "i18n").glob("es*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        yield str(path.relative_to(ROOT)), "\n".join(_json_strings(data))
    yield "README.md", (ROOT / "README.md").read_text(encoding="utf-8")


def missing_accents(text: str, *, english_ok: bool = True) -> list[str]:
    hits = []
    for m in ACCENT_RE.finditer(text):
        word = m.group(0)
        if english_ok and word.lower() in ALLOWED:
            continue
        hits.append(word)
    return hits


@pytest.mark.parametrize("label,text", list(spanish_visible_sources()), ids=lambda x: x if isinstance(x, str) and len(x) < 60 else "")
def test_spanish_visible_text_has_accents(label, text):
    # Code spans and URLs are identifiers, not prose.
    prose = re.sub(r"`[^`]*`|https?://\S+|\([^)]*\.md\)", " ", text)
    hits = missing_accents(prose)
    assert not hits, f"{label}: missing accents in {sorted(set(hits))[:20]}"


def test_the_guard_itself_catches_what_it_should():
    # Negative check: the guard must fail on the exact strings of the old site.
    for bad in ("Analisis", "senal", "Calibracion", "sintetico", "Pistas de senal",
                "Mapa de saturacion", "tambien", "numero"):
        assert missing_accents(bad), bad
    for good in ("Análisis", "señal", "Calibración", "sintético", "que", "como",
                 "esta", "mas", "versión", "región", "variaciones"):
        assert not missing_accents(good), good
